apiVersion: v1
kind: Secret
metadata:
  name: greenops-secrets
  namespace: greenops
type: Opaque
stringData:
  postgres-user: greenops
  postgres-password: greenops_password
  postgres-db: greenops_db
  grafana-client-secret: super-secret-grafana-key
