apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: greenops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: accounts.greenops.local
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_RELATIVE_PATH
              value: /
            - name: KC_PROXY
              value: edge
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HTTP_CORS_ALLOWED_ORIGINS
              value: "https://greenops.local"
            - name: KC_HTTP_CORS_ALLOWED_METHODS
              value: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            - name: KC_HTTP_CORS_ALLOWED_HEADERS
              value: "Authorization,Content-Type,X-Requested-With,Origin"
            - name: KC_HTTP_CORS_EXPOSED_HEADERS
              value: "WWW-Authenticate"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: realm-config
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/login/theme.properties
              subPath: theme.properties
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/common/resources/css/main.css
              subPath: main.css
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/common/resources/css/overrides.css
              subPath: overrides.css
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/common/resources/js/runtime.js
              subPath: runtime.js
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/common/resources/js/main.js
              subPath: main.js
            - name: theme
              mountPath: /opt/keycloak/themes/greenops/common/resources/js/split/911-4e9cc94ab88075badbbf.js
              subPath: 911-4e9cc94ab88075badbbf.js
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm
        - name: theme
          configMap:
            name: keycloak-theme
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: greenops
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
