apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: greenops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: "greenops-grafana"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: greenops-secrets
                  key: grafana-client-secret
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: "https://accounts.greenops.local/realms/greenops/protocol/openid-connect/auth"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "http://keycloak:8080/realms/greenops/protocol/openid-connect/token"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "http://keycloak:8080/realms/greenops/protocol/openid-connect/userinfo"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS
              value: "greenops.local accounts.greenops.local monitor.greenops.local"
            - name: GF_AUTH_GENERIC_OAUTH_REDIRECT_URI
              value: "https://monitor.greenops.local/login/generic_oauth"
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: "openid profile email"
            - name: GF_AUTH_GENERIC_OAUTH_SKIP_VERIFY_SSL
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "https://monitor.greenops.local/"
            - name: GF_LOG_LEVEL
              value: "debug"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: greenops
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
