services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: greenops
      POSTGRES_PASSWORD: greenops_password
      POSTGRES_DB: greenops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json

  alerts-service:
    build:
      context: ../../
      dockerfile: apps/alerts-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://greenops:greenops_password@postgres:5432/greenops_db?schema=public
      PORT: 3001
    depends_on:
      - postgres

  user-service:
    build:
      context: ../../
      dockerfile: apps/user-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://greenops:greenops_password@postgres:5432/greenops_db?schema=public
      PORT: 3003
    depends_on:
      - postgres

  nginx:
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - alerts-service
      - user-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
