services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: greenops
      POSTGRES_PASSWORD: greenops_password
      POSTGRES_DB: greenops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: accounts.greenops.local
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /
      KC_PROXY: edge
    ports:
      - "8080:8080"
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json

  alerts-service:
    build:
      context: ../../
      dockerfile: apps/alerts-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://greenops:greenops_password@postgres:5432/greenops_db?schema=public
      PORT: 3001
    depends_on:
      - postgres

  user-service:
    build:
      context: ../../
      dockerfile: apps/user-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://greenops:greenops_password@postgres:5432/greenops_db?schema=public
      PORT: 3003
    depends_on:
      - postgres

  nginx:
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - alerts-service
      - user-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    extra_hosts:
      - "accounts.greenops.local:host-gateway"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "greenops-grafana"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "your-client-secret"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://accounts.greenops.local/realms/greenops/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://accounts.greenops.local/realms/greenops/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://accounts.greenops.local/realms/greenops/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS: "greenops.local accounts.greenops.local monitor.greenops.local"
      GF_AUTH_GENERIC_OAUTH_REDIRECT_URI: "https://monitor.greenops.local/login/generic_oauth"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_SKIP_VERIFY_SSL: "true"
      GF_SERVER_ROOT_URL: "https://monitor.greenops.local/"
    depends_on:
      - prometheus

volumes:
  postgres_data:
