server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/alerts/ {
        rewrite ^/api/alerts/(.*) /$1 break;
        proxy_pass http://alerts-service:3001;
    }

    location /api/user/ {
        rewrite ^/api/user/(.*) /$1 break;
        proxy_pass http://user-service:3003;
    }
}
